//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JszxDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class classtimes_tb
    {
        public classtimes_tb()
        {
            this.schedule_tb = new HashSet<schedule_tb>();
        }
    
        public int ClsTmIndex { get; set; }
        public string ClsTmName { get; set; }
        public System.TimeSpan ClsTmStart { get; set; }
        public System.TimeSpan ClsTmEnd { get; set; }
    
        public virtual ICollection<schedule_tb> schedule_tb { get; set; }
    }
}
