//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JszxDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class courses_tb
    {
        public courses_tb()
        {
            this.schedule_tb = new HashSet<schedule_tb>();
        }
    
        public int CrsID { get; set; }
        public string CrsName { get; set; }
        public string CrsTeacher { get; set; }
        public string CrsClasses { get; set; }
        public Nullable<float> CrsHour { get; set; }
        public Nullable<int> CrsTimes { get; set; }
        public Nullable<int> CrsNum { get; set; }
        public string CrsConf { get; set; }
        public string CrsRemark { get; set; }
    
        public virtual ICollection<schedule_tb> schedule_tb { get; set; }
    }
}
