//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JszxDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class exprecords_tb
    {
        public long RecordID { get; set; }
        public string CourseName { get; set; }
        public string ExpName { get; set; }
        public string ExpClasses { get; set; }
        public Nullable<int> Shoulder { get; set; }
        public Nullable<int> Realizer { get; set; }
        public Nullable<int> Groups { get; set; }
        public Nullable<int> PerGroup { get; set; }
        public string StudentStatus { get; set; }
        public string InstrumentStatus { get; set; }
        public string Problems { get; set; }
        public string TeacherName { get; set; }
        public string TeacherNumber { get; set; }
        public string StudentName { get; set; }
        public Nullable<sbyte> ExpCls { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
        public string ExpLab { get; set; }
        public Nullable<int> ExpTerm { get; set; }
        public Nullable<sbyte> ExpWeek { get; set; }
        public Nullable<sbyte> ExpWeekDay { get; set; }
    
        public virtual terms_tb terms_tb { get; set; }
    }
}
