//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JszxDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class labs_tb
    {
        public labs_tb()
        {
            this.exprecords_tb = new HashSet<exprecords_tb>();
            this.schedule_tb = new HashSet<schedule_tb>();
        }
    
        public int LabID { get; set; }
        public string LabName { get; set; }
        public Nullable<int> LabAdmin { get; set; }
        public string LabAddr { get; set; }
        public string LabIP { get; set; }
        public string LabKeyWord { get; set; }
    
        public virtual admins_tb admins_tb { get; set; }
        public virtual ICollection<exprecords_tb> exprecords_tb { get; set; }
        public virtual ICollection<schedule_tb> schedule_tb { get; set; }
    }
}
