//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JszxDataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class terms_tb
    {
        public terms_tb()
        {
            this.exprecords_tb = new HashSet<exprecords_tb>();
            this.schedule_tb = new HashSet<schedule_tb>();
        }
    
        public int TermID { get; set; }
        public string TermYear { get; set; }
        public bool TermIndex { get; set; }
        public System.DateTime TermStartDay { get; set; }
        public sbyte TermWeeks { get; set; }
        public bool TermIsUse { get; set; }
    
        public virtual ICollection<exprecords_tb> exprecords_tb { get; set; }
        public virtual ICollection<schedule_tb> schedule_tb { get; set; }
    }
}
